### ISSUE TITLE
Object of type 'Site' is not JSON serializable ... on /api/pages

### ISSUE THREAD

**Issue by baumann** [divio/djangocms-rest-api#17]
Hey there,

I am getting an exception, when I open the URL /api/pages.
(/api works fine)

Here the exception and list of packages/versions:

```
Internal Server Error: /api/pages/
Traceback (most recent call last):
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 701, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 659, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 409, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 103, in render
    separators=separators
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/Users/user1/workspace/venv/lib/python3.6/site-packages/rest_framework/utils/encoders.py", line 70, in default
    return super(JSONEncoder, self).default(obj)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Site' is not JSON serializable
```

I work on a **Mac** using **Python3**.
Here the packages I have installed:
```
cmsplugin-filer==1.1.3
dj-database-url==0.5.0
Django==1.11.10
django-appconf==1.0.2
django-classy-tags==0.8.0
django-cms==3.5.0
django-cors-headers==1.3.1
django-filer==1.3.0
django-filter==1.1.0
django-formtools==2.1
django-mptt==0.8.7
django-polymorphic==1.3
django-reversion==1.8.7
django-sekizai==0.10.0
Django-Select2==5.8.9
django-treebeard==4.2.0
djangocms-admin-style==1.2.7
djangocms-attributes-field==0.3.0
djangocms-column==1.7.0
djangocms-file==2.0.2
djangocms-googlemap==1.1.1
djangocms-installer==1.0.0
djangocms-link==2.1.2
djangocms-picture==2.0.6
djangocms-rest-api==0.2.0
djangocms-snippet==2.0.0
djangocms-style==2.0.2
djangocms-text-ckeditor==3.3.1
djangocms-video==2.0.4
djangorestframework==3.5.2
easy-thumbnails==2.5
html5lib==0.9999999
Markdown==2.6.11
Pillow==5.0.0
PyHamcrest==1.9.0
pytz==2018.3
six==1.11.0
tzlocal==1.5.1
Unidecode==0.4.21
```

Any recommendations on how to fix this?

**Comment by maurovanetti** [comment]
Same issue here on Ubuntu Linux with Python 3.6 and the following packages installed:

aldryn-addons (1.0.2)
aldryn-boilerplates (0.7.7)
aldryn-client (2.3.5)
aldryn-django (1.11.11.1)
aldryn-django-cms (3.5.1.3)
aldryn-sites (0.5.8)
aldryn-snake (0.0.2)
aldryn-sso (1.1.16)
asn1crypto (0.24.0)
boto (2.48.0)
certifi (2018.1.18)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
cmsplugin-filer (1.1.3)
cryptography (2.2.1)
dj-database-url (0.5.0)
dj-email-url (0.0.10)
dj-redis-url (0.1.4)
dj-static (0.0.6)
Django (1.11.11)
django-appconf (1.0.2)
django-cache-url (2.0.0)
django-classy-tags (0.8.0)
django-cms (3.5.1)
django-compressor (2.2)
django-debreach (1.4.2)
django-filer (1.3.0.1)
django-formtools (2.1)
django-getenv (1.3.2)
django-mptt (0.8.7)
django-parler (1.9.2)
django-polymorphic (1.3)
django-ranged-response (0.2.0)
django-reversion (1.8.7)
django-robots (3.0)
django-sekizai (0.10.0)
django-select2 (6.0.2)
django-simple-captcha (0.5.6)
django-simple-sso (0.12.0)
django-sortedm2m (1.5.0)
django-storages (1.6.5)
django-treebeard (4.2.1)
djangocms-admin-style (1.2.7)
djangocms-attributes-field (0.3.0)
djangocms-rest-api (0.2.0)
djangorestframework (3.4.7)
djeese-fs (0.1.21)
easy-thumbnails (2.5)
furl (1.0.1)
idna (2.6)
itsdangerous (0.24)
lxml (4.2.1)
ndg-httpsclient (0.4.4)
opbeat (3.6.1)
orderedmultidict (0.7.11)
Pillow (5.0.0)
pip (9.0.3)
psycopg2 (2.7.4)
pyasn1 (0.4.2)
pycparser (2.18)
pyOpenSSL (17.5.0)
pytz (2018.3)
raven (6.6.0)
rcssmin (1.0.6)
requests (2.18.4)
rjsmin (1.0.12)
setuptools (39.0.1)
six (1.11.0)
static3 (0.7.0)
structlog (18.1.0)
tabulate (0.8.2)
Unidecode (0.4.21)
urllib3 (1.22)
uWSGI (2.0.17)
webservices (0.7)
wheel (0.30.0)
YURL (0.13)

**Comment by mightym** [comment]
Same here. Bare Django CMS installation + djangocms-rest-api

**Comment by appsembly-team** [comment]
same here

**Comment by mvanderlinde** [comment]
+1

**Comment by SandPipper** [comment]
same here

**Comment by SandPipper** [comment]
Please note that Pages model no longer have 'site' field -> /usr/local/lib/python3.6/site-packages/rest_framework/fields.py:102: UserWarning: Pages no longer have a "site" field. To get the site object of any given page, call "site" on the page "node" object. This backwards compatible shim will be removed in version 3.6'. So in PageSerializer in fields change 'site' to 'node'.

**Comment by chriscslaughter** [comment]
Has anyone figured out a resolution to this?

**Comment by SandPipper** [comment]
There are my fork where I fixed this issue and I am planning to maintain the fork.  https://github.com/SandPipper/djangocms-rest-api

**Comment by bunny1985** [comment]
same for me . anyone?
